name: "Pip"

on:
  push:
  pull_request:

jobs:
  build-pyodide:
    runs-on: ubuntu-latest

    env:
      PYODIDE_VERSION: 0.23.1
      PYTHON_VERSION: 3.11.2
      EMSCRIPTEN_VERSION: 3.1.32
      NODE_VERSION: 18
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - uses: mymindstorm/setup-emsdk@ab889da2abbcbb280f91ec4c215d3bb4f3a8f775 # v12
      with:
        version: ${{ env.EMSCRIPTEN_VERSION }}
        actions-cache-folder: emsdk-cache

    - name: Install pyodide-build
      run: pip install "pydantic<2" pyodide-build==$PYODIDE_VERSION

    - name: Build
      run: |
        # Pyodide is still in the process of adding better/easier support for
        # non-setup.py based builds.
        CFLAGS=-g2 LDFLAGS=-g2 pyodide build
